
name: Deploy CD

on:

  # Run on push on production branches
  push:
    branches:
      # Production
      - main
      - master

  # Run on manual triggers
  workflow_dispatch:

# Set GITHUB_TOKEN permissions for the workflow
permissions:
  contents: read

# Set workflow concurrency rules
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:

  # Build job
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Pages
      uses: actions/configure-pages@v2

    - name: Check PHP version
      run: php --version

    - name: Compile site with PHP script
      run: php build.php

    - name: Build with Jekyll
      uses: actions/jekyll-build-pages@v1
      with:
        source: ./
        destination: ./_site

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1

  # Deploy job
  deploy:
    runs-on: ubuntu-latest

    # Job dependencies
    needs:
      - build

    # Set GITHUB_TOKEN permissions for the job
    permissions:
      pages: write
      id-token: write

    # Set deployment environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
